name: trabalhoFinal_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.0
  geolocator: ^5.1.3
  google_maps_flutter: ^0.5.11
  location: ^3.0.0
  map_view: ^1.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
